-- liquibase formatted sql

-- changeset plexdownloader:001-users
CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plex_account_id VARCHAR(255) NOT NULL UNIQUE,
    username   VARCHAR(255) NOT NULL,
    avatar_url TEXT,
    role       VARCHAR(20) NOT NULL DEFAULT 'USER',
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- changeset plexdownloader:001-settings
CREATE TABLE settings (
    key   VARCHAR(100) PRIMARY KEY,
    value TEXT
);

-- changeset plexdownloader:001-movies
CREATE TABLE movies (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plex_id     VARCHAR(100) NOT NULL UNIQUE,
    title       VARCHAR(500) NOT NULL,
    year        INT,
    summary     TEXT,
    poster_url  TEXT,
    file_path   TEXT,
    duration_ms BIGINT,
    synced_at   TIMESTAMP
);
CREATE TABLE movie_genres (
    movie_id BIGINT NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    genre    VARCHAR(100) NOT NULL
);

-- changeset plexdownloader:001-tvshows
CREATE TABLE tv_shows (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plex_id    VARCHAR(100) NOT NULL UNIQUE,
    title      VARCHAR(500) NOT NULL,
    year       INT,
    summary    TEXT,
    poster_url TEXT,
    synced_at  TIMESTAMP
);
CREATE TABLE show_genres (
    show_id BIGINT NOT NULL REFERENCES tv_shows(id) ON DELETE CASCADE,
    genre   VARCHAR(100) NOT NULL
);

-- changeset plexdownloader:001-seasons
CREATE TABLE seasons (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plex_id        VARCHAR(100) NOT NULL UNIQUE,
    show_id        BIGINT NOT NULL REFERENCES tv_shows(id) ON DELETE CASCADE,
    season_number  INT NOT NULL,
    title          VARCHAR(255),
    poster_url     TEXT,
    episode_count  INT,
    synced_at      TIMESTAMP
);

-- changeset plexdownloader:001-episodes
CREATE TABLE episodes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plex_id          VARCHAR(100) NOT NULL UNIQUE,
    season_id        BIGINT NOT NULL REFERENCES seasons(id) ON DELETE CASCADE,
    episode_number   INT NOT NULL,
    title            VARCHAR(500),
    summary          TEXT,
    thumbnail_url    TEXT,
    file_path        TEXT,
    duration_ms      BIGINT,
    air_date         DATE,
    director         VARCHAR(500),
    writer           VARCHAR(500),
    video_resolution VARCHAR(50),
    synced_at        TIMESTAMP
);

-- changeset plexdownloader:001-actors
CREATE TABLE actors (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plex_id   VARCHAR(100) NOT NULL UNIQUE,
    name      VARCHAR(255) NOT NULL,
    photo_url TEXT
);
CREATE TABLE movie_actors (
    movie_id BIGINT NOT NULL REFERENCES movies(id)  ON DELETE CASCADE,
    actor_id BIGINT NOT NULL REFERENCES actors(id)  ON DELETE CASCADE,
    role     VARCHAR(255),
    PRIMARY KEY (movie_id, actor_id)
);
CREATE TABLE show_actors (
    show_id  BIGINT NOT NULL REFERENCES tv_shows(id) ON DELETE CASCADE,
    actor_id BIGINT NOT NULL REFERENCES actors(id)   ON DELETE CASCADE,
    role     VARCHAR(255),
    PRIMARY KEY (show_id, actor_id)
);

-- changeset plexdownloader:001-download-queue
CREATE TABLE download_queue (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users(id),
    media_type     VARCHAR(20) NOT NULL,
    media_id       BIGINT NOT NULL,
    status         VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    queue_position INT,
    error_message  TEXT,
    requested_at   TIMESTAMP NOT NULL DEFAULT NOW(),
    completed_at   TIMESTAMP
);
CREATE INDEX idx_download_queue_status ON download_queue(status);
